/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/cut-string`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more-info`; params?: Router.UnknownInputParams; } | { pathname: `/requests`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/assets/Checkmark`; params?: Router.UnknownInputParams; } | { pathname: `/assets/Fail`; params?: Router.UnknownInputParams; } | { pathname: `/requests/get-access-token`; params?: Router.UnknownInputParams; } | { pathname: `/types/user`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/constants`; params?: Router.UnknownOutputParams; } | { pathname: `/cut-string`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/more-info`; params?: Router.UnknownOutputParams; } | { pathname: `/requests`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/assets/Checkmark`; params?: Router.UnknownOutputParams; } | { pathname: `/assets/Fail`; params?: Router.UnknownOutputParams; } | { pathname: `/requests/get-access-token`; params?: Router.UnknownOutputParams; } | { pathname: `/types/user`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/constants${`?${string}` | `#${string}` | ''}` | `/cut-string${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/more-info${`?${string}` | `#${string}` | ''}` | `/requests${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/assets/Checkmark${`?${string}` | `#${string}` | ''}` | `/assets/Fail${`?${string}` | `#${string}` | ''}` | `/requests/get-access-token${`?${string}` | `#${string}` | ''}` | `/types/user${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/cut-string`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more-info`; params?: Router.UnknownInputParams; } | { pathname: `/requests`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/assets/Checkmark`; params?: Router.UnknownInputParams; } | { pathname: `/assets/Fail`; params?: Router.UnknownInputParams; } | { pathname: `/requests/get-access-token`; params?: Router.UnknownInputParams; } | { pathname: `/types/user`; params?: Router.UnknownInputParams; };
    }
  }
}
